site_name: AgedCoderReboot
site_url: https://zuohd.github.io/AgedCoderReboot/
repo_url: https://github.com/zuohd/AgedCoderReboot
repo_name: AgedCoderReboot
site_description: 大龄程序员成长智库 & 自救指南
site_author: Houde Zuo (Soderberg)

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - content.code.copy

nav:
  - 首页: index.md
  - 成长指南:
      - 职业转型: guides/career-transition.md
      - Web3 方向: guides/web3.md
      - 参与开源: guides/open-source.md
  - 心理支持: mindset.md
  - 推荐资源: resources.md

markdown_extensions:
  - toc:
      permalink: true
  - footnotes
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight
